<?php

echo $this->subMenu;

echo '<div id="contentPage">';

    
    echo '<br />';

    
    echo '<p class="toffParagraph">';
        echo 'Projekt je zanimiv za vse sponzorje, ki želijo bodisi razširiti svoje delovanje onkraj oceana 
        ali pa povečati prepoznavnost med študenti, na celotnem ljubljanskem območju in tudi v celotni Sloveniji. 
        V društvu bomo poskrbeli, da bo dogodek čim bolj odmeven ter ga bo moč zaslediti na številnih komunikacijskih
         kanalih. Naše sponzorje bomo predstavili in promovirali na vseh spremljajočih aktivnostih glavnega dogodka,
          prav tako ga bomo tudi vključili v vse publikacije in v kolikor bo le mogoče, tudi v novice za medije in 
          spletne portale.';
    echo '</p>';
    
    echo '<p class="toffParagraph">';
        echo 'Promocijo naših sponzorjev si predstavljamo v dveh delih. Prvi del predstavlja promocijo v slovenskem prostoru. Ta bo potekala preko medijev, socialnih omrežij, mailing list, spletnih portalov, forumov in seveda na spremljajočemu potopisnemu predavanju. Velik obisk naše spletne strani bomo zagotovili z objavami  zanimivosti in vsakodnevnega povzetka dneva ekskurzije. Prek društva elektrotehnikov stromar.si imamo dobro povezavo z mediji, ki smo jo ustvarili v preteklem delovanju, zato pričakujemo sodelovanje tudi pri tem dogodku in s tem povečanje odmevnosti dogodka, posledično pa tudi vašega podjetja, v kolikor nas bo pri projektu finančno podprlo. Kar nekaj spletnih medijev pa imamo tudi v lasti društva (spremlja nas okoli 2000 študentov).';
    echo '</p>';
    
    echo '<p class="toffParagraph">';
        echo 'Drugi del promocije vašega podjetja sestavlja predstavitev na ozemlju Združenih držav Amerike. Logo sponzorjev bomo nosili na naših majicah, naredili pa bomo tudi zastavo z logoti sponzorjev in magnetne nalepke za na kombi. ';
    echo '</p>';
    
    echo '<p class="toffParagraph">';
        echo 'Pričakujemo, da nas bo v Sloveniji spremljalo okoli 1000 študentov Univerze v Ljubljani, večinoma iz Fakultete za elektrotehniko. Ocenjujemo, da se jih bo cca. 300 udeležilo tudi potopisnega predavanja. Verjamemo, da nas bo preko interneta in publikacij spremljalo še cca. 80 študentov izven Univerze v Ljubljane in okoli 40 preostalih interesentov, ki niso študentje (po večini novinarji in zaposleni na FE).';   
    echo '</p>';
    
    echo '<div align="center">';
        echo '<table id="sponsorTypeTable">';

            echo '<tr>';
                echo '<td style="color:#ff0000;">';
                    echo 'Generalni sponzor';
                echo '</td>';
                echo '<td class="amount">';
                    echo 'vsaj 3.000 €';
                echo '</td>';
            echo '</tr>';

            echo '<tr>';
                echo '<td style="color:#ffc000">';
                    echo 'Zlati sponzorji';
                echo '</td>';
                echo '<td class="amount">';
                    echo 'vsaj 1.500 €';
                echo '</td>';
            echo '</tr>';

            echo '<tr>';
                echo '<td style="color:#bfbfbf">';
                    echo 'Srebrni sponzorji';
                echo '</td>';
                echo '<td class="amount">';
                    echo 'vsaj 800 €';
                echo '</td>';
            echo '</tr>';

            echo '<tr>';
                echo '<td style="color:#984806">';
                    echo 'Bronasti sponzorji';
                echo '</td>';
                echo '<td class="amount">';
                    echo 'vsaj 400 €';
                echo '</td>';
            echo '</tr>';

            echo '<tr>';
                echo '<td style="color:#000000">';
                    echo 'Ostali sponzorji';
                echo '</td>';
                echo '<td class="amount">';
                    echo 'vsaj 100 €';
                echo '</td>';
            echo '</tr>';  
        echo '</table>';   	 
    echo '</div>';
    
    
    // offer table
    echo '<table id="offerTable">';
    
        echo '<tr>';
            echo '<th></th>';
            echo '<th></th>';
            echo '<th class="sType">Ostali</th>';
            echo '<th class="sType">Bronasti</th>';
            echo '<th class="sType">Srebrni</th>';
            echo '<th class="sType">Zlati</th>';
            echo '<th class="sType">Generalni</th>';
        echo '</tr>';
    
        echo '<tr>';
            echo '<td>1.</td>';
            echo '<td>';
                echo 'Ime ekskurzije po nazivu podjetja »naziv podjetja FE ZDA TRIP«.';
            echo '</td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';
        
        echo '<tr>';
            echo '<td>2.</td>';
            echo '<td>';
                echo 'Lastni razstavni pano med izvajanjem potopisnega predavanja (priskrbi sponzor).';
            echo '</td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';
        
        echo '<tr>';
            echo '<td>3.</td>';
            echo '<td>';
                echo 'Promocijsko predavanje do 3 min (na dan potopisnega predavanja) v  okviru uvodnega pozdrava.';
            echo '</td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';
        
        echo '<tr>';
            echo '<td>4.</td>';
            echo '<td>';
                echo 'Zahvala generalnemu sponzorju na koncu posnetkov videodnevnika na Youtube kanalu  http://www.youtube.com/user/feusa2012.';
            echo '</td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';
        
        echo '<tr>';
            echo '<td>5.</td>';
            echo '<td>';
                echo 'Velikost logota na platnih in majicah je petkrat večja od ostalih sponzorjev. Logo se nahaja na sredini.';
            echo '</td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';
        
        echo '<tr>';
            echo '<td>6.</td>';
            echo '<td>';
                echo 'Organizirano potopisno predavanje na sedežu podjetja.';
            echo '</td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';
        
        echo '<tr>';
            echo '<td>7.</td>';
            echo '<td>';
                echo 'Magnetne »nalepke« na kombiju. ';
            echo '</td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';  
        
        echo '<tr>';
            echo '<td>8.</td>';
            echo '<td>';
                echo 'Organiziran ogled podjetja študentov FE (s pomočjo Študentske organizacije Fakultete za elektrotehniko).';
            echo '</td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';
        
        echo '<tr>';
            echo '<td>9.</td>';
            echo '<td>';
                echo 'Anorak z vašim logotom in imenom ekskurzije, ki ga bomo nosili ob slabšem vremenu.';
            echo '</td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';
        
        echo '<tr>';
            echo '<td>10.</td>';
            echo '<td>';
                echo 'Velikost logota na platnih in majicah je štirikrat večja od ostalih sponzorjev. Logo se nahaja poleg logota generalnega sponzorja.';
            echo '</td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';  
   
        echo '<tr>';
            echo '<td>11.</td>';
            echo '<td>';
                echo 'Velikost logota na platnih in majicah je trikrat večja od ostalih sponzorjev.';
            echo '</td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';      
         
        echo '<tr>';
            echo '<td>12.</td>';
            echo '<td>';
                echo 'Kratek opis pokrovitelja na spletni strani.';
            echo '</td>';
            echo '<td></td>';
            echo '<td></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';  
   
        echo '<tr>';
            echo '<td>13.</td>';
            echo '<td>';
                echo 'Logotip na glavni strani ter vseh podstraneh.';
            echo '</td>';
            echo '<td></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';         
        
        echo '<tr>';
            echo '<td>14.</td>';
            echo '<td>';
                echo 'Velikost logota na platnih in majicah je trikrat večja od ostalih sponzorjev.';
            echo '</td>';
            echo '<td></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';  
   
        echo '<tr>';
            echo '<td>15.</td>';
            echo '<td>';
                echo 'Oglaševanje storitev sponzorjev na spletni strani.';
            echo '</td>';
            echo '<td></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';    
        
        echo '<tr>';
            echo '<td>16.</td>';
            echo '<td>';
                echo 'Logotip na glavni strani spletne strani z aktivno povezavo.';
            echo '</td>';
            echo '<td></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
        echo '</tr>'; 
        
        echo '<tr>';
            echo '<td>17.</td>';
            echo '<td>';
                echo 'Logotip na velikem platnu in na majici članov ekipe.';
            echo '</td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';    
        
        echo '<tr>';
            echo '<td>18.</td>';
            echo '<td>';
                echo 'Logotip na spletni strani pod rubriko pokrovitelji.';
            echo '</td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';
        
        echo '<tr>';
            echo '<td>19.</td>';
            echo '<td>';  
                echo 'Pregled sponzorjev na koncu predstavitvenega videa.';
            echo '</td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
            echo '<td class="checked"></td>';
        echo '</tr>';
    echo '</table>';

    
    
echo '</div>';
