<script src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
new TWTR.Widget({
  version: 2,
  type: 'profile',
  rpp: 4,
  interval: 30000,
  width: 265,
  height: 300,
  theme: {
    shell: {
      background: '#0887ea',
      color: '#ffffff'
    },
    tweets: {
      background: '#ffffff',
      color: '#313131',
      links: '#00afdb'
    }
  },
  features: {
    scrollbar: false,
    loop: false,
    live: false,
    behavior: 'all'
  }
}).render().setUser('feusa2012').start();
</script>