<?php

echo '<div id="blog">';

echo '<h1>';
    echo $this->translate('Blog');
echo '</h1>';

echo '<div style="margin-top:30px;">';
    echo 'Blog še ni na voljo!';
echo '</div>';
/*
echo '<table>';

foreach ($this->blogs as $blog) {
    
    echo '<tr>';
        echo '<td>';
        
            echo '<div class="blogItem">';
                echo '<h2>';
                    echo $blog['title'];
                echo '</h2>';
            
                echo '<div>';
                    echo $blog['content'];
                echo '</div>';
            echo '</div>';
        
        echo '</td>';
    echo '</tr>';
    
    
    
}


echo '</table>';
*/
echo '</div>';